openapi: 3.2.0
info:
  title: Roboflow Inference Server Doctr API
  description: Roboflow inference server
  termsOfService: https://roboflow.com/terms
  contact:
    name: Roboflow Inc.
    url: https://roboflow.com/contact
    email: help@roboflow.com
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.3.8
tags:
- name: Doctr
paths:
  /doctr/ocr:
    post:
      summary: DocTR OCR response
      description: Run the DocTR OCR model to retrieve text in an image.
      operationId: doctr_retrieve_text_doctr_ocr_post
      parameters:
      - name: api_key
        in: query
        required: false
        schema:
          anyOf:
          - type: string
          - type: 'null'
          description: Roboflow API Key that will be passed to the model during initialization for artifact
            retrieval
          title: Api Key
        description: Roboflow API Key that will be passed to the model during initialization for artifact
          retrieval
      - name: countinference
        in: query
        required: false
        schema:
          anyOf:
          - type: boolean
          - type: 'null'
          title: Countinference
      - name: service_secret
        in: query
        required: false
        schema:
          anyOf:
          - type: string
          - type: 'null'
          title: Service Secret
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DoctrOCRInferenceRequest'
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                anyOf:
                - $ref: '#/components/schemas/OCRInferenceResponse'
                - type: array
                  items:
                    $ref: '#/components/schemas/OCRInferenceResponse'
                title: Response Doctr Retrieve Text Doctr Ocr Post
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
      tags:
      - Doctr
components:
  schemas:
    DoctrOCRInferenceRequest:
      properties:
        id:
          type: string
          title: Id
        api_key:
          anyOf:
          - type: string
          - type: 'null'
          title: Api Key
          description: Roboflow API Key that will be passed to the model during initialization for artifact
            retrieval
        usage_billable:
          type: boolean
          title: Usage Billable
          default: true
        start:
          anyOf:
          - type: number
          - type: 'null'
          title: Start
        source:
          anyOf:
          - type: string
          - type: 'null'
          title: Source
        source_info:
          anyOf:
          - type: string
          - type: 'null'
          title: Source Info
        stream_pipeline_context_id:
          anyOf:
          - type: string
          - type: 'null'
          title: Stream Pipeline Context Id
          description: Internal stream-pipeline frame pairing id. Not part of the public API.
        disable_model_monitoring:
          anyOf:
          - type: boolean
          - type: 'null'
          title: Disable Model Monitoring
          description: If true, disables model monitoring for this request
          default: false
        image:
          anyOf:
          - items:
              $ref: '#/components/schemas/InferenceRequestImage'
            type: array
          - $ref: '#/components/schemas/InferenceRequestImage'
          title: Image
        doctr_version_id:
          anyOf:
          - type: string
          - type: 'null'
          title: Doctr Version Id
          default: default
        model_id:
          anyOf:
          - type: string
          - type: 'null'
          title: Model Id
        generate_bounding_boxes:
          anyOf:
          - type: boolean
          - type: 'null'
          title: Generate Bounding Boxes
          default: false
      type: object
      required:
      - id
      - image
      title: DoctrOCRInferenceRequest
      description: "DocTR inference request.\n\nAttributes:\n    api_key (Optional[str]): Roboflow API\
        \ Key."
    HTTPValidationError:
      properties:
        detail:
          items:
            $ref: '#/components/schemas/ValidationError'
          type: array
          title: Detail
      type: object
      title: HTTPValidationError
    OCRInferenceResponse:
      properties:
        result:
          type: string
          title: Result
          description: The combined OCR recognition result.
        image:
          anyOf:
          - $ref: '#/components/schemas/InferenceResponseImage'
          - type: 'null'
          description: Metadata about input image dimensions
        predictions:
          anyOf:
          - items:
              $ref: '#/components/schemas/ObjectDetectionPrediction'
            type: array
          - type: 'null'
          title: Predictions
          description: List of objects detected by OCR
        time:
          type: number
          title: Time
          description: The time in seconds it took to produce the inference including preprocessing.
        parent_id:
          anyOf:
          - type: string
          - type: 'null'
          title: Parent Id
          description: Identifier of parent image region. Useful when stack of detection-models is in
            use to refer the RoI being the input to inference
      type: object
      required:
      - result
      - time
      title: OCRInferenceResponse
      description: "OCR Inference response.\n\nAttributes:\n    result (str): The combined OCR recognition\
        \ result.\n    predictions (List[ObjectDetectionPrediction]): List of objects detected by OCR\n\
        \    time (float): The time in seconds it took to produce the inference including preprocessing"
    InferenceRequestImage:
      properties:
        type:
          type: string
          title: Type
          description: The type of image data provided, one of 'url', 'base64', or 'numpy'
          examples:
          - url
        value:
          anyOf:
          - {}
          - type: 'null'
          title: Value
          description: Image data corresponding to the image type, if type = 'url' then value is a string
            containing the url of an image, else if type = 'base64' then value is a string containing
            base64 encoded image data, else if type = 'numpy' then value is binary numpy data serialized
            using pickle.dumps(); array should 3 dimensions, channels last, with values in the range [0,255].
          examples:
          - http://www.example-image-url.com
      type: object
      required:
      - type
      title: InferenceRequestImage
      description: "Image data for inference request.\n\nAttributes:\n    type (str): The type of image\
        \ data provided, one of 'url', 'base64', or 'numpy'.\n    value (Optional[Any]): Image data corresponding\
        \ to the image type."
    InferenceResponseImage:
      properties:
        width:
          type: integer
          title: Width
          description: The original width of the image used in inference
        height:
          type: integer
          title: Height
          description: The original height of the image used in inference
      type: object
      required:
      - width
      - height
      title: InferenceResponseImage
      description: "Inference response image information.\n\nAttributes:\n    width (int): The original\
        \ width of the image used in inference.\n    height (int): The original height of the image used\
        \ in inference."
    ObjectDetectionPrediction:
      properties:
        x:
          type: number
          title: X
          description: The center x-axis pixel coordinate of the prediction
        y:
          type: number
          title: Y
          description: The center y-axis pixel coordinate of the prediction
        width:
          type: number
          title: Width
          description: The width of the prediction bounding box in number of pixels
        height:
          type: number
          title: Height
          description: The height of the prediction bounding box in number of pixels
        confidence:
          type: number
          title: Confidence
          description: The detection confidence as a fraction between 0 and 1
        class:
          type: string
          title: Class
          description: The predicted class label
        class_confidence:
          anyOf:
          - type: number
          - type: 'null'
          title: Class Confidence
          description: The class label confidence as a fraction between 0 and 1
        class_id:
          type: integer
          title: Class Id
          description: The class id of the prediction
        tracker_id:
          anyOf:
          - type: integer
          - type: 'null'
          title: Tracker Id
          description: The tracker id of the prediction if tracking is enabled
        detection_id:
          type: string
          title: Detection Id
          description: Unique identifier of detection
        parent_id:
          anyOf:
          - type: string
          - type: 'null'
          title: Parent Id
          description: Identifier of parent image region. Useful when stack of detection-models is in
            use to refer the RoI being the input to inference
      type: object
      required:
      - x
      - y
      - width
      - height
      - confidence
      - class
      - class_id
      title: ObjectDetectionPrediction
      description: "Object Detection prediction.\n\nAttributes:\n    x (float): The center x-axis pixel\
        \ coordinate of the prediction.\n    y (float): The center y-axis pixel coordinate of the prediction.\n\
        \    width (float): The width of the prediction bounding box in number of pixels.\n    height\
        \ (float): The height of the prediction bounding box in number of pixels.\n    confidence (float):\
        \ The detection confidence as a fraction between 0 and 1.\n    class_name (str): The predicted\
        \ class label.\n    class_confidence (Union[float, None]): The class label confidence as a fraction\
        \ between 0 and 1.\n    class_id (int): The class id of the prediction"
    ValidationError:
      properties:
        loc:
          items:
            anyOf:
            - type: string
            - type: integer
          type: array
          title: Location
        msg:
          type: string
          title: Message
        type:
          type: string
          title: Error Type
      type: object
      required:
      - loc
      - msg
      - type
      title: ValidationError
